"""
Charge le referentiel ANSSI en base de donnees.
Source : https://www.cert.ssi.gouv.fr/uploads/guide-ad.html
Executer une fois au deploiement, puis lors des mises a jour du referentiel.
Idempotent : peut etre relance sans dupliquer les entrees.
"""
import sys
from pathlib import Path

# Allow running as standalone script
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sqlalchemy.orm import Session

from app.core.database import SessionLocal
from app.models.anssi_checklist import AnssiCheckpoint

ANSSI_CHECKPOINTS = [
    # ═══ NIVEAU 1 — Critique ═══
    {
        "vuln_id": "vuln1_permissions_naming_context",
        "level": 1,
        "title_fr": "Chemins de contrôle dangereux vers la racine des naming contexts",
        "description": "Des chemins de contrôle dangereux existent vers les racines LDAP de l'AD (naming contexts). Un attaquant peut prendre le contrôle complet de l'Active Directory.",
        "recommendation": "Enlever les permissions dangereuses sur les naming contexts. Correction via ADSI Edit ou ldp. Vérifier les permissions Exchange et Azure ADConnect.",
        "category": "permissions",
        "required_attributes": ["nTSecurityDescriptor", "distinguishedName"],
        "target_object_types": ["domain_root", "configuration", "schema"],
        "auto_checkable": True,
        "severity_score": 100,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#permissions_naming_context",
    },
    {
        "vuln_id": "vuln1_permissions_adminsdholder",
        "level": 1,
        "title_fr": "Permissions dangereuses sur l'objet adminSDHolder",
        "description": "Des permissions dangereuses sur adminSDHolder permettent de prendre le contrôle complet de l'AD. Cassent l'étanchéité du Tier 0.",
        "recommendation": "Revenir aux permissions par défaut sur adminSDHolder via ADSI Edit ou ldp.",
        "category": "permissions",
        "required_attributes": ["nTSecurityDescriptor"],
        "target_object_types": ["adminsdholder"],
        "auto_checkable": True,
        "severity_score": 100,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#permissions_adminsdholder",
    },
    {
        "vuln_id": "vuln1_permissions_dc",
        "level": 1,
        "title_fr": "Chemins de contrôle dangereux vers les contrôleurs de domaine",
        "description": "Des chemins de contrôle permettent de prendre le contrôle des DC, répliquant ainsi les secrets de tous les comptes.",
        "recommendation": "Les comptes avec permissions sur les DC doivent être protégés par adminSDHolder. Appartenir aux groupes Administrateurs de l'entreprise ou du domaine.",
        "category": "permissions",
        "required_attributes": ["nTSecurityDescriptor", "userAccountControl"],
        "target_object_types": ["computer"],
        "auto_checkable": True,
        "severity_score": 100,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#permissions_dc",
    },
    {
        "vuln_id": "vuln1_permissions_dpapi",
        "level": 1,
        "title_fr": "Chemins de contrôle dangereux vers les clés DPAPI",
        "description": "Un attaquant ayant la clé DPAPI du domaine peut déchiffrer tous les secrets protégés par DPAPI.",
        "recommendation": "Ne pas modifier les permissions par défaut des clés DPAPI. Correction via ADSI Edit.",
        "category": "permissions",
        "required_attributes": ["nTSecurityDescriptor"],
        "target_object_types": ["dpapi_key"],
        "auto_checkable": True,
        "severity_score": 95,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#permissions_dpapi",
    },
    {
        "vuln_id": "vuln1_permissions_gmsa_keys",
        "level": 1,
        "title_fr": "Chemins de contrôle dangereux vers les clés gMSA",
        "description": "Un attaquant peut récupérer le mot de passe des gMSA en contrôlant leurs clés KDS.",
        "recommendation": "Revenir aux permissions par défaut avec Dsacls <DN> /S /T.",
        "category": "permissions",
        "required_attributes": ["nTSecurityDescriptor"],
        "target_object_types": ["gmsa"],
        "auto_checkable": True,
        "severity_score": 90,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#permissions_gmsa_keys",
    },
    {
        "vuln_id": "vuln1_permissions_dfsr_sysvol",
        "level": 1,
        "title_fr": "Chemins de contrôle dangereux vers les paramètres DFSR du SYSVOL",
        "description": "Un attaquant peut modifier le SYSVOL et faire exécuter des GPO malveillantes sur les DC.",
        "recommendation": "Revenir aux permissions par défaut sur les paramètres DFSR.",
        "category": "permissions",
        "required_attributes": ["nTSecurityDescriptor"],
        "target_object_types": ["dfsr"],
        "auto_checkable": True,
        "severity_score": 95,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#permissions_dfsr_sysvol",
    },
    {
        "vuln_id": "vuln1_permissions_schema",
        "level": 1,
        "title_fr": "Chemins de contrôle dangereux vers les objets du schéma",
        "description": "Le contrôle du schéma permet de prendre le contrôle complet de l'AD.",
        "recommendation": "Revenir aux permissions par défaut avec Dsacls <DN> /S /T.",
        "category": "permissions",
        "required_attributes": ["nTSecurityDescriptor"],
        "target_object_types": ["schema"],
        "auto_checkable": True,
        "severity_score": 100,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#permissions_schema",
    },
    {
        "vuln_id": "vuln1_permissions_msdns",
        "level": 1,
        "title_fr": "Chemins de contrôle dangereux vers les serveurs MicrosoftDNS",
        "description": "Écriture sur CN=MicrosoftDNS,CN=System permet d'exécuter du code arbitraire sur le service DNS (hébergé par un DC).",
        "recommendation": "Retirer la permission d'écriture. Créer une délégation manuelle via ldp.",
        "category": "dns",
        "required_attributes": ["nTSecurityDescriptor"],
        "target_object_types": ["dns_container"],
        "auto_checkable": True,
        "severity_score": 90,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#permissions_msdns",
    },
    {
        "vuln_id": "vuln1_permissions_gpo_priv",
        "level": 1,
        "title_fr": "Chemins de contrôle dangereux vers les GPO des groupes privilégiés",
        "description": "Un attaquant contrôlant ces GPO peut exécuter du code sur les machines des admins et élever ses privilèges.",
        "recommendation": "Revoir les permissions sur les objets GPO via ADSI Edit ou ldp.",
        "category": "permissions",
        "required_attributes": ["nTSecurityDescriptor", "gPCFileSysPath"],
        "target_object_types": ["gpo"],
        "auto_checkable": True,
        "severity_score": 90,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#permissions_gpo_priv",
    },
    {
        "vuln_id": "vuln1_privileged_members",
        "level": 1,
        "title_fr": "Nombre important de membres des groupes privilégiés",
        "description": "La forêt contient plus de 50 comptes privilégiés, empêchant un contrôle efficace.",
        "recommendation": "Mettre en place un modèle de délégation. Groupes opératifs : vides. Groupes forêt : peuplés temporairement.",
        "category": "accounts",
        "required_attributes": ["memberOf", "adminCount", "objectSid", "primaryGroupID"],
        "target_object_types": ["user", "group"],
        "auto_checkable": True,
        "severity_score": 80,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#privileged_members",
    },
    {
        "vuln_id": "vuln1_privileged_members_perm",
        "level": 1,
        "title_fr": "Chemins de contrôle dangereux vers des membres de groupes privilégiés",
        "description": "Des droits permettent à des utilisateurs non privilégiés de contrôler des comptes privilégiés.",
        "recommendation": "Enlever les permissions dangereuses. Corriger via ADSI Edit ou ldp.",
        "category": "permissions",
        "required_attributes": ["nTSecurityDescriptor", "adminCount", "memberOf"],
        "target_object_types": ["user"],
        "auto_checkable": True,
        "severity_score": 95,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#privileged_members_perm",
    },
    {
        "vuln_id": "vuln1_delegation_a2d2",
        "level": 1,
        "title_fr": "Délégation contrainte vers un service d'un contrôleur de domaine",
        "description": "Permet au compte d'élever ses privilèges auprès du DC.",
        "recommendation": "Supprimer dans msDS-AllowedToDelegateTo tous les SPN référençant des DC.",
        "category": "delegation",
        "required_attributes": ["msDS-AllowedToDelegateTo", "userAccountControl"],
        "target_object_types": ["user", "computer"],
        "auto_checkable": True,
        "severity_score": 95,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#delegation_a2d2",
    },
    {
        "vuln_id": "vuln1_delegation_t2a4d",
        "level": 1,
        "title_fr": "Délégation contrainte avec transition de protocole vers un DC",
        "description": "Permet de s'authentifier auprès d'un DC avec l'identité d'un autre utilisateur sans pré-auth.",
        "recommendation": "Supprimer dans msDS-AllowedToDelegateTo tous les SPN référençant des DC.",
        "category": "delegation",
        "required_attributes": ["msDS-AllowedToDelegateTo", "userAccountControl"],
        "target_object_types": ["user", "computer"],
        "auto_checkable": True,
        "severity_score": 95,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#delegation_t2a4d",
    },
    {
        "vuln_id": "vuln1_delegation_sourcedeleg",
        "level": 1,
        "title_fr": "Délégation contrainte basée sur les ressources sur des DC",
        "description": "Resource-based constrained delegation configurée sur des DC, accorde une délégation complète.",
        "recommendation": "Supprimer l'attribut msDS-AllowedToActOnBehalfOfOtherIdentity sur les DC.",
        "category": "delegation",
        "required_attributes": ["msDS-AllowedToActOnBehalfOfOtherIdentity"],
        "target_object_types": ["computer"],
        "auto_checkable": True,
        "severity_score": 95,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#delegation_sourcedeleg",
    },
    {
        "vuln_id": "vuln1_kerberos_properties_preauth_priv",
        "level": 1,
        "title_fr": "Comptes privilégiés sans pré-authentification Kerberos",
        "description": "Permet d'obtenir un ticket chiffré et de lancer une attaque brute force sur le mot de passe.",
        "recommendation": "Supprimer DONT_REQUIRE_PREAUTH et changer le mot de passe.",
        "category": "kerberos",
        "required_attributes": ["userAccountControl", "adminCount"],
        "target_object_types": ["user"],
        "auto_checkable": True,
        "severity_score": 90,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#kerberos_properties_preauth_priv",
    },
    {
        "vuln_id": "vuln1_spn_priv",
        "level": 1,
        "title_fr": "Comptes privilégiés avec SPN",
        "description": "Un SPN sur un compte privilégié permet le Kerberoasting — attaque brute force sur le ticket.",
        "recommendation": "Supprimer le SPN des comptes privilégiés et changer leur mot de passe. Ou utiliser des gMSA.",
        "category": "kerberos",
        "required_attributes": ["servicePrincipalName", "adminCount", "memberOf"],
        "target_object_types": ["user"],
        "auto_checkable": True,
        "severity_score": 90,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#spn_priv",
    },
    {
        "vuln_id": "vuln1_dont_expire_priv",
        "level": 1,
        "title_fr": "Comptes privilégiés dont le mot de passe n'expire jamais",
        "description": "La récupération d'un tel compte permet de conserver les droits sur le long terme.",
        "recommendation": "Supprimer DONT_EXPIRE et renouveler le mot de passe (max tous les 3 ans).",
        "category": "password_policy",
        "required_attributes": ["userAccountControl", "adminCount"],
        "target_object_types": ["user"],
        "auto_checkable": True,
        "severity_score": 85,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#dont_expire_priv",
    },
    {
        "vuln_id": "vuln1_password_change_priv",
        "level": 1,
        "title_fr": "Comptes privilégiés dont le mot de passe est inchangé depuis plus de 3 ans",
        "description": "Un mot de passe inchangé depuis 3 ans augmente le risque de compromission à long terme.",
        "recommendation": "Mettre en œuvre une politique de renouvellement < 3 ans pour les comptes privilégiés.",
        "category": "password_policy",
        "required_attributes": ["pwdLastSet", "adminCount"],
        "target_object_types": ["user"],
        "auto_checkable": True,
        "severity_score": 85,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#password_change_priv",
    },
    {
        "vuln_id": "vuln1_password_change_dc_no_change",
        "level": 1,
        "title_fr": "DC dont le mot de passe de compte d'ordinateur est inchangé depuis plus de 45 jours",
        "description": "Les DC doivent changer automatiquement leur mot de passe tous les 30 jours. Un défaut indique un dysfonctionnement.",
        "recommendation": "Vérifier les registres DisablePasswordChange et MaximumPasswordAge. S'assurer qu'aucune GPO ne les modifie.",
        "category": "password_policy",
        "required_attributes": ["pwdLastSet", "userAccountControl"],
        "target_object_types": ["computer"],
        "auto_checkable": True,
        "severity_score": 85,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#password_change_dc_no_change",
    },
    {
        "vuln_id": "vuln1_password_change_inactive_dc",
        "level": 1,
        "title_fr": "Contrôleurs de domaine inactifs",
        "description": "Des DC ne se sont pas authentifiés depuis plus de 45 jours, signe de désynchronisation.",
        "recommendation": "Réinstaller ou supprimer les DC désynchronisés. Utiliser Djoin pour la jonction hors connexion.",
        "category": "configuration",
        "required_attributes": ["lastLogonTimestamp", "userAccountControl"],
        "target_object_types": ["computer"],
        "auto_checkable": True,
        "severity_score": 80,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#password_change_inactive_dc",
    },
    {
        "vuln_id": "vuln1_dc_inconsistent_uac",
        "level": 1,
        "title_fr": "Contrôleurs de domaine incohérents",
        "description": "Attributs dans un état incohérent, symptomatique d'erreur de config ou de malveillance.",
        "recommendation": "Vérifier userAccountControl (SERVER_TRUST_ACCOUNT|TRUSTED_FOR_DELEGATION = 0x82000).",
        "category": "configuration",
        "required_attributes": ["userAccountControl", "serverReferenceBL"],
        "target_object_types": ["computer"],
        "auto_checkable": True,
        "severity_score": 85,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#dc_inconsistent_uac",
    },
    {
        "vuln_id": "vuln1_adcs_control",
        "level": 1,
        "title_fr": "Chemins de contrôle dangereux vers les conteneurs de certificats",
        "description": "Permet d'ajouter une CA malveillante et d'usurper des utilisateurs.",
        "recommendation": "Revenir aux permissions par défaut sur les conteneurs de certificats.",
        "category": "certificates",
        "required_attributes": ["nTSecurityDescriptor"],
        "target_object_types": ["pki_container"],
        "auto_checkable": True,
        "severity_score": 95,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#adcs_control",
    },
    {
        "vuln_id": "vuln1_adcs_template_control",
        "level": 1,
        "title_fr": "Chemins de contrôle dangereux vers les modèles de certificats",
        "description": "Permet de faire générer un certificat arbitraire par la CA pour usurper n'importe quel utilisateur.",
        "recommendation": "Revenir aux permissions par défaut sur les templates via adsiedit.msc ou pkiview.msc.",
        "category": "certificates",
        "required_attributes": ["nTSecurityDescriptor"],
        "target_object_types": ["cert_template"],
        "auto_checkable": True,
        "severity_score": 95,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#adcs_template_control",
    },
    {
        "vuln_id": "vuln1_certificates_vuln",
        "level": 1,
        "title_fr": "Certificats faibles ou vulnérables (critique)",
        "description": "Utilisation de DSA, clé RSA < 1024 bits, ou clé vulnérable à ROCA.",
        "recommendation": "Révoquer et regénérer avec RSA ≥ 2048 bits et algorithme SHA-2/SHA-3.",
        "category": "certificates",
        "required_attributes": ["cACertificate", "userCertificate"],
        "target_object_types": ["pki_container", "user", "computer"],
        "auto_checkable": True,
        "severity_score": 90,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#certificates_vuln",
    },
    {
        "vuln_id": "vuln1_dnsadmins",
        "level": 1,
        "title_fr": "Comptes membres du groupe DnsAdmins",
        "description": "Les membres de DnsAdmins peuvent exécuter du code arbitraire sur le service DNS hébergé par un DC.",
        "recommendation": "Vider le groupe DnsAdmins. Créer une délégation manuelle via ldp.",
        "category": "dns",
        "required_attributes": ["memberOf", "objectSid"],
        "target_object_types": ["user", "group"],
        "auto_checkable": True,
        "severity_score": 85,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#dnsadmins",
    },
    {
        "vuln_id": "vuln1_dnszone_bad_prop",
        "level": 1,
        "title_fr": "Zones DNS mal configurées (critique)",
        "description": "ZONE_UPDATE_UNSECURE permet la mise à jour DNS sans authentification.",
        "recommendation": "Reconfigurer pour mises à jour sécurisées uniquement : dnscmd /Config <zone> /AllowUpdate 2.",
        "category": "dns",
        "required_attributes": ["dNSProperty"],
        "target_object_types": ["dns_zone"],
        "auto_checkable": True,
        "severity_score": 80,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#dnszone_bad_prop",
    },
    {
        "vuln_id": "vuln1_dsheuristics_bad",
        "level": 1,
        "title_fr": "Paramètres dSHeuristics dangereux (critique)",
        "description": "fAllowAnonNSPI ≠ 0 ou dwAdminSDExMask ≠ 0 affaiblit la sécurité de l'AD.",
        "recommendation": "Remettre fAllowAnonNSPI et dwAdminSDExMask à 0 via ADSI Edit.",
        "category": "configuration",
        "required_attributes": ["dSHeuristics"],
        "target_object_types": ["directory_service"],
        "auto_checkable": True,
        "severity_score": 90,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#dsheuristics_bad",
    },
    {
        "vuln_id": "vuln1_trusts_domain_notfiltered",
        "level": 1,
        "title_fr": "Relations d'approbation sortante non filtrées",
        "description": "Un attaquant ayant compromis le domaine externe peut usurper n'importe quel utilisateur du domaine.",
        "recommendation": "Activer la quarantaine : netdom trust <domaine> /domain:<externe> /Quarantine:yes.",
        "category": "trusts",
        "required_attributes": ["trustDirection", "trustType", "trustAttributes"],
        "target_object_types": ["trust"],
        "auto_checkable": True,
        "severity_score": 90,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#trusts_domain_notfiltered",
    },
    {
        "vuln_id": "vuln1_trusts_forest_sidhistory",
        "level": 1,
        "title_fr": "Relations d'approbation forêt avec sID History activé",
        "description": "Filtrage affaibli permettant l'usurpation d'identité depuis la forêt externe.",
        "recommendation": "Réactiver le filtrage : netdom trust <forêt> /domain:<externe> /EnableSIDHistory:no.",
        "category": "trusts",
        "required_attributes": ["trustDirection", "trustType", "trustAttributes"],
        "target_object_types": ["trust"],
        "auto_checkable": True,
        "severity_score": 90,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#trusts_forest_sidhistory",
    },
    {
        "vuln_id": "vuln1_user_accounts_dormant",
        "level": 1,
        "title_fr": "Nombre important de comptes actifs inutilisés",
        "description": "Plus de 25% de comptes dormants (non authentifiés depuis > 1 an). Risque de comptes obsolètes exploitables.",
        "recommendation": "Neutraliser les comptes obsolètes : désactiver, retirer des groupes, randomiser le mot de passe.",
        "category": "accounts",
        "required_attributes": ["lastLogonTimestamp", "pwdLastSet", "userAccountControl"],
        "target_object_types": ["user", "computer"],
        "auto_checkable": True,
        "severity_score": 70,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#user_accounts_dormant",
    },
    {
        "vuln_id": "vuln1_primary_group_id_1000",
        "level": 1,
        "title_fr": "Comptes avec un PrimaryGroupID inférieur à 1000",
        "description": "Les PrimaryGroupID < 1000 sont souvent privilégiés. Permet de dissimuler l'appartenance à un groupe admin.",
        "recommendation": "Repositionner les primaryGroupId aux valeurs par défaut (513, 515, 516, 521).",
        "category": "accounts",
        "required_attributes": ["primaryGroupID"],
        "target_object_types": ["user", "computer"],
        "auto_checkable": True,
        "severity_score": 80,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#primary_group_id_1000",
    },
    # ═══ NIVEAU 2 — Lacunes ═══
    {
        "vuln_id": "vuln2_privileged_members_password",
        "level": 2,
        "title_fr": "Comptes privilégiés avec une mauvaise politique de mot de passe",
        "description": "Politique de mot de passe faible imposée aux comptes privilégiés.",
        "recommendation": "Renouvellement max 3 ans, longueur min 8 caractères. Ne pas forcer un renouvellement trop fréquent.",
        "category": "password_policy",
        "required_attributes": ["pwdLastSet", "adminCount", "msDS-ResultantPSO"],
        "target_object_types": ["user"],
        "auto_checkable": True,
        "severity_score": 70,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#privileged_members_password",
    },
    {
        "vuln_id": "vuln2_delegation_t4d",
        "level": 2,
        "title_fr": "Délégation d'authentification non contrainte",
        "description": "Permet d'usurper l'identité de tout utilisateur s'authentifiant auprès de ces comptes.",
        "recommendation": "Supprimer TRUSTED_FOR_DELEGATION. Utiliser la délégation contrainte si nécessaire.",
        "category": "delegation",
        "required_attributes": ["userAccountControl"],
        "target_object_types": ["user", "computer"],
        "auto_checkable": True,
        "severity_score": 75,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#delegation_t4d",
    },
    {
        "vuln_id": "vuln2_kerberos_properties_preauth",
        "level": 2,
        "title_fr": "Comptes sans pré-authentification Kerberos",
        "description": "Permet le AS-REP Roasting sur des comptes non privilégiés.",
        "recommendation": "Supprimer DONT_REQUIRE_PREAUTH et changer le mot de passe.",
        "category": "kerberos",
        "required_attributes": ["userAccountControl"],
        "target_object_types": ["user"],
        "auto_checkable": True,
        "severity_score": 65,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#kerberos_properties_preauth",
    },
    {
        "vuln_id": "vuln2_kerberos_properties_deskey",
        "level": 2,
        "title_fr": "Comptes utilisateurs avec chiffrement Kerberos DES",
        "description": "USE_DES_KEY_ONLY autorise un chiffrement obsolète, facilitant le brute force.",
        "recommendation": "Retirer USE_DES_KEY_ONLY de l'attribut userAccountControl.",
        "category": "kerberos",
        "required_attributes": ["userAccountControl"],
        "target_object_types": ["user"],
        "auto_checkable": True,
        "severity_score": 65,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#kerberos_properties_deskey",
    },
    {
        "vuln_id": "vuln2_dont_expire",
        "level": 2,
        "title_fr": "Comptes dont le mot de passe n'expire jamais",
        "description": "La récupération d'un tel compte permet de conserver les droits sur le long terme.",
        "recommendation": "Supprimer DONT_EXPIRE. Documenter les comptes de service et leurs procédures de rotation.",
        "category": "password_policy",
        "required_attributes": ["userAccountControl"],
        "target_object_types": ["user"],
        "auto_checkable": True,
        "severity_score": 60,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#dont_expire",
    },
    {
        "vuln_id": "vuln2_password_change_server_no_change_90",
        "level": 2,
        "title_fr": "Serveurs dont le mot de passe est inchangé depuis plus de 90 jours",
        "description": "Les serveurs doivent changer automatiquement leur mot de passe tous les 30 jours.",
        "recommendation": "Vérifier les registres DisablePasswordChange et MaximumPasswordAge.",
        "category": "password_policy",
        "required_attributes": ["pwdLastSet", "userAccountControl", "operatingSystem"],
        "target_object_types": ["computer"],
        "auto_checkable": True,
        "severity_score": 60,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#password_change_server_no_change_90",
    },
    {
        "vuln_id": "vuln2_sysvol_ntfrs",
        "level": 2,
        "title_fr": "Utilisation de NTFRS pour la réplication du SYSVOL",
        "description": "NTFRS est obsolète et n'est plus supporté par les dernières versions de Windows Server.",
        "recommendation": "Migrer vers DFSR. Voir documentation Microsoft sur la migration NTFRS → DFSR.",
        "category": "replication",
        "required_attributes": ["fRSMemberReferenceBL"],
        "target_object_types": ["computer"],
        "auto_checkable": True,
        "severity_score": 55,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#sysvol_ntfrs",
    },
    {
        "vuln_id": "vuln2_adupdate_bad",
        "level": 2,
        "title_fr": "Mauvaises versions de l'Active Directory",
        "description": "Schéma en révision 15 créant des ACE trop permissives pour Key Admins et Enterprise Key Admins.",
        "recommendation": "Mettre à jour le schéma avec adprep /ForestPrep puis adprep /DomainPrep.",
        "category": "configuration",
        "required_attributes": ["objectVersion"],
        "target_object_types": ["schema"],
        "auto_checkable": True,
        "severity_score": 60,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#adupdate_bad",
    },
    {
        "vuln_id": "vuln2_compatible_2000_anonymous",
        "level": 2,
        "title_fr": "Pre-Windows 2000 Compatible Access contient Anonymous",
        "description": "Permet une énumération anonyme d'éléments sur les DC.",
        "recommendation": "Le groupe ne doit contenir que Utilisateurs authentifiés (S-1-5-11).",
        "category": "configuration",
        "required_attributes": ["member", "objectSid"],
        "target_object_types": ["group"],
        "auto_checkable": True,
        "severity_score": 60,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#compatible_2000_anonymous",
    },
    {
        "vuln_id": "vuln2_krbtgt",
        "level": 2,
        "title_fr": "Mot de passe du compte krbtgt inchangé depuis plus d'un an",
        "description": "Compromission du krbtgt permet de forger des golden tickets et s'authentifier partout.",
        "recommendation": "Changer le mot de passe krbtgt annuellement (2 fois, avec délai entre les deux).",
        "category": "password_policy",
        "required_attributes": ["pwdLastSet", "sAMAccountName"],
        "target_object_types": ["user"],
        "auto_checkable": True,
        "severity_score": 75,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#krbtgt",
    },
    {
        "vuln_id": "vuln2_rodc_priv_revealed",
        "level": 2,
        "title_fr": "Comptes privilégiés dans les attributs de révélation des RODC",
        "description": "Des comptes privilégiés ont leurs secrets révélés (cachés) sur des RODC.",
        "recommendation": "Retirer les comptes privilégiés des listes de révélation RODC.",
        "category": "rodc",
        "required_attributes": ["msDS-RevealedUsers", "msDS-NeverRevealGroup", "msDS-RevealOnDemandGroup"],
        "target_object_types": ["computer"],
        "auto_checkable": True,
        "severity_score": 70,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#rodc_priv_revealed",
    },
    {
        "vuln_id": "vuln2_sidhistory_dangerous",
        "level": 2,
        "title_fr": "Comptes avec historique de SID d'apparence non conforme",
        "description": "sIDHistory contenant des SID de groupes privilégiés permet une élévation de privilèges furtive.",
        "recommendation": "Supprimer les sIDHistory non conformes des comptes concernés.",
        "category": "accounts",
        "required_attributes": ["sIDHistory", "objectSid"],
        "target_object_types": ["user", "group"],
        "auto_checkable": True,
        "severity_score": 70,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#sidhistory_dangerous",
    },
    {
        "vuln_id": "vuln2_trusts_accounts",
        "level": 2,
        "title_fr": "Comptes de trust dont le mot de passe est inchangé depuis plus d'un an",
        "description": "Les comptes de trust doivent être renouvelés régulièrement.",
        "recommendation": "Renouveler les mots de passe des comptes de trust.",
        "category": "trusts",
        "required_attributes": ["pwdLastSet", "trustDirection"],
        "target_object_types": ["trust"],
        "auto_checkable": True,
        "severity_score": 60,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#trusts_accounts",
    },
    # ═══ NIVEAU 3 — Basique ═══
    {
        "vuln_id": "vuln3_password_change_server_no_change_45",
        "level": 3,
        "title_fr": "Serveurs dont le mot de passe est inchangé depuis plus de 45 jours",
        "description": "Les serveurs doivent changer automatiquement leur mot de passe (30 jours par défaut).",
        "recommendation": "Vérifier les registres DisablePasswordChange et MaximumPasswordAge.",
        "category": "password_policy",
        "required_attributes": ["pwdLastSet", "userAccountControl", "operatingSystem"],
        "target_object_types": ["computer"],
        "auto_checkable": True,
        "severity_score": 45,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#password_change_server_no_change_45",
    },
    {
        "vuln_id": "vuln3_password_change_inactive_servers",
        "level": 3,
        "title_fr": "Serveurs inactifs",
        "description": "Des serveurs ne se sont pas authentifiés depuis plus de 45 jours.",
        "recommendation": "Réinstaller ou supprimer les serveurs désynchronisés.",
        "category": "configuration",
        "required_attributes": ["lastLogonTimestamp", "userAccountControl", "operatingSystem"],
        "target_object_types": ["computer"],
        "auto_checkable": True,
        "severity_score": 40,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#password_change_inactive_servers",
    },
    {
        "vuln_id": "vuln3_protected_users",
        "level": 3,
        "title_fr": "Comptes privilégiés non membres du groupe Protected Users",
        "description": "Le groupe Protected Users applique des protections supplémentaires (pas de NTLM, pas de délégation).",
        "recommendation": "Ajouter les comptes privilégiés au groupe Protected Users.",
        "category": "accounts",
        "required_attributes": ["memberOf", "adminCount"],
        "target_object_types": ["user"],
        "auto_checkable": True,
        "severity_score": 45,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#protected_users",
    },
    {
        "vuln_id": "vuln3_reversible_password",
        "level": 3,
        "title_fr": "Comptes ayant leur mot de passe stocké de manière réversible",
        "description": "Permet la récupération du mot de passe en clair depuis la base AD.",
        "recommendation": "Supprimer le flag ENCRYPTED_TEXT_PASSWORD_ALLOWED et changer le mot de passe.",
        "category": "password_policy",
        "required_attributes": ["userAccountControl"],
        "target_object_types": ["user"],
        "auto_checkable": True,
        "severity_score": 50,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#reversible_password",
    },
    {
        "vuln_id": "vuln3_owner",
        "level": 3,
        "title_fr": "Objets ayant un propriétaire inadapté",
        "description": "Des propriétaires non privilégiés sur des objets sensibles permettent de modifier les ACL.",
        "recommendation": "Corriger les propriétaires des objets sensibles.",
        "category": "permissions",
        "required_attributes": ["nTSecurityDescriptor"],
        "target_object_types": ["user", "computer", "group", "gpo"],
        "auto_checkable": True,
        "severity_score": 45,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#owner",
    },
    {
        "vuln_id": "vuln3_sidhistory_present",
        "level": 3,
        "title_fr": "Comptes ou groupes ayant un historique de SID",
        "description": "sIDHistory doit être nettoyé après les migrations.",
        "recommendation": "Supprimer les sIDHistory des comptes/groupes concernés.",
        "category": "accounts",
        "required_attributes": ["sIDHistory"],
        "target_object_types": ["user", "group"],
        "auto_checkable": True,
        "severity_score": 35,
        "reference_url": "https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#sidhistory_present",
    },
]


def seed(db: Session) -> dict[str, int]:
    """Upsert all ANSSI checkpoints. Returns {"inserted": n, "updated": m}."""
    inserted = 0
    updated = 0

    for data in ANSSI_CHECKPOINTS:
        existing = (
            db.query(AnssiCheckpoint)
            .filter(AnssiCheckpoint.vuln_id == data["vuln_id"])
            .first()
        )
        if existing:
            for key, value in data.items():
                setattr(existing, key, value)
            updated += 1
        else:
            db.add(AnssiCheckpoint(**data))
            inserted += 1

    db.commit()
    return {"inserted": inserted, "updated": updated}


def main() -> None:
    db = SessionLocal()
    try:
        result = seed(db)
        total = result["inserted"] + result["updated"]
        print(
            f"Referentiel ANSSI : {total} checkpoints "
            f"({result['inserted']} inseres, {result['updated']} mis a jour)"
        )
    finally:
        db.close()


if __name__ == "__main__":
    main()
