// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../../src/app/audits/evaluation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audits/evaluation">> = Specific
  const handler = {} as typeof import("../../../../src/app/audits/evaluation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/audits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audits">> = Specific
  const handler = {} as typeof import("../../../../src/app/audits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/entreprises/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/entreprises">> = Specific
  const handler = {} as typeof import("../../../../src/app/entreprises/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/equipements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/equipements">> = Specific
  const handler = {} as typeof import("../../../../src/app/equipements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/frameworks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/frameworks">> = Specific
  const handler = {} as typeof import("../../../../src/app/frameworks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/outils/ad-auditor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/outils/ad-auditor">> = Specific
  const handler = {} as typeof import("../../../../src/app/outils/ad-auditor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/outils/collecte/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/outils/collecte">> = Specific
  const handler = {} as typeof import("../../../../src/app/outils/collecte/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/outils/config-parser/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/outils/config-parser">> = Specific
  const handler = {} as typeof import("../../../../src/app/outils/config-parser/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/outils/network-map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/outils/network-map">> = Specific
  const handler = {} as typeof import("../../../../src/app/outils/network-map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/outils/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/outils">> = Specific
  const handler = {} as typeof import("../../../../src/app/outils/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/outils/pingcastle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/outils/pingcastle">> = Specific
  const handler = {} as typeof import("../../../../src/app/outils/pingcastle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/outils/scanner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/outils/scanner">> = Specific
  const handler = {} as typeof import("../../../../src/app/outils/scanner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/outils/ssl-checker/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/outils/ssl-checker">> = Specific
  const handler = {} as typeof import("../../../../src/app/outils/ssl-checker/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/sites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sites">> = Specific
  const handler = {} as typeof import("../../../../src/app/sites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
