// Re-export shared constants used across audits sub-components
export {
  AUDIT_STATUS_LABELS as STATUS_LABELS,
  AUDIT_STATUS_VARIANTS as STATUS_VARIANTS,
  AUDIT_STATUS_ICONS as STATUS_ICONS,
  CAMPAIGN_STATUS_LABELS as CAMPAIGN_LABELS,
  COMPLIANCE_LABELS_SHORT as COMPLIANCE_LABELS,
  COMPLIANCE_COLORS as COMPLIANCE_CLASSES,
  SEVERITY_VARIANTS,
} from "@/lib/constants";
