"""create_checklist_tables

Revision ID: 43d973779ca0
Revises: 41f4dca76503
Create Date: 2026-03-31 15:01:33.428838
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '43d973779ca0'
down_revision: Union[str, None] = '41f4dca76503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_predefined', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('checklist_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_sections_template_id'), ['template_id'], unique=False)

    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('ref_code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['checklist_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_items_section_id'), ['section_id'], unique=False)

    op.create_table('checklist_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('filled_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'in_progress', 'completed')", name='ck_checklist_status'),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'audit_id', 'site_id', name='uq_checklist_instance')
    )
    with op.batch_alter_table('checklist_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_instances_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_instances_filled_by'), ['filled_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_instances_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_instances_template_id'), ['template_id'], unique=False)
        batch_op.create_index('uix_checklist_instance_no_site', ['template_id', 'audit_id'], unique=True, sqlite_where=sa.text('site_id IS NULL'), postgresql_where=sa.text('site_id IS NULL'))

    op.create_table('checklist_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('responded_by', sa.Integer(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('OK', 'NOK', 'NA', 'UNCHECKED')", name='ck_checklist_response_status'),
    sa.ForeignKeyConstraint(['instance_id'], ['checklist_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['checklist_items.id'], ),
    sa.ForeignKeyConstraint(['responded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'item_id', name='uq_checklist_response')
    )
    with op.batch_alter_table('checklist_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_responses_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_responses_item_id'), ['item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_responses_item_id'))
        batch_op.drop_index(batch_op.f('ix_checklist_responses_instance_id'))

    op.drop_table('checklist_responses')
    with op.batch_alter_table('checklist_instances', schema=None) as batch_op:
        batch_op.drop_index('uix_checklist_instance_no_site', sqlite_where=sa.text('site_id IS NULL'), postgresql_where=sa.text('site_id IS NULL'))
        batch_op.drop_index(batch_op.f('ix_checklist_instances_template_id'))
        batch_op.drop_index(batch_op.f('ix_checklist_instances_site_id'))
        batch_op.drop_index(batch_op.f('ix_checklist_instances_filled_by'))
        batch_op.drop_index(batch_op.f('ix_checklist_instances_audit_id'))

    op.drop_table('checklist_instances')
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_items_section_id'))

    op.drop_table('checklist_items')
    with op.batch_alter_table('checklist_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_sections_template_id'))

    op.drop_table('checklist_sections')
    op.drop_table('checklist_templates')
    # ### end Alembic commands ###
