"""remove_archive_path_from_monkey365

Revision ID: 5f73dd19afec
Revises: 008_add_monkey365_archive_path
Create Date: 2026-03-25 18:50:08.361140
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision: str = '5f73dd19afec'
down_revision: Union[str, None] = '008_add_monkey365_archive_path'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monkey365_scan_results', 'auth_mode')
    op.drop_column('monkey365_scan_results', 'archive_path')
    op.drop_column('monkey365_scan_results', 'force_msal_desktop')
    op.drop_column('monkey365_scan_results', 'powershell_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monkey365_scan_results', sa.Column('powershell_config', sqlite.JSON(), nullable=True))
    op.add_column('monkey365_scan_results', sa.Column('force_msal_desktop', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
    op.add_column('monkey365_scan_results', sa.Column('archive_path', sa.VARCHAR(length=500), nullable=True))
    op.add_column('monkey365_scan_results', sa.Column('auth_mode', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
