"""add_collect_pipeline

Revision ID: 5fe6333fd834
Revises: 0dbf56cd8db3
Create Date: 2026-04-15 20:04:23.588707
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5fe6333fd834'
down_revision: Union[str, None] = '0dbf56cd8db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collect_pipelines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='pipelinestatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('scan_status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='pipelinestepstatus'), nullable=False),
    sa.Column('hosts_discovered', sa.Integer(), nullable=False),
    sa.Column('equipments_status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='pipelinestepstatus'), nullable=False),
    sa.Column('equipments_created', sa.Integer(), nullable=False),
    sa.Column('hosts_skipped', sa.Integer(), nullable=False),
    sa.Column('collects_status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='pipelinestepstatus'), nullable=False),
    sa.Column('collects_total', sa.Integer(), nullable=False),
    sa.Column('collects_done', sa.Integer(), nullable=False),
    sa.Column('collects_failed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans_reseau.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collect_pipelines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collect_pipelines_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_collect_pipelines_scan_id'), ['scan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collect_pipelines_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collect_pipelines_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collect_pipelines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collect_pipelines_status'))
        batch_op.drop_index(batch_op.f('ix_collect_pipelines_site_id'))
        batch_op.drop_index(batch_op.f('ix_collect_pipelines_scan_id'))
        batch_op.drop_index(batch_op.f('ix_collect_pipelines_created_by'))

    op.drop_table('collect_pipelines')
    # Nettoyage des types ENUM PostgreSQL (non supprimés automatiquement par drop_table)
    sa.Enum(name='pipelinestatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='pipelinestepstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
